-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 13:17:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Escuela` ;

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escuela` ;
USE `Escuela` ;

-- -----------------------------------------------------
-- Table `Escuela`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escuela`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `Escuela`.`Profesor` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escuela`.`Materia` ;

CREATE TABLE IF NOT EXISTS `Escuela`.`Materia` (
  `CodigoMateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `grado` FLOAT NOT NULL,
  PRIMARY KEY (`CodigoMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escuela`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `Escuela`.`Alumno` (
  `Identificacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `curso` TEXT(10) NULL,
  `Materia_CodigoMateria` INT NOT NULL,
  PRIMARY KEY (`Identificacion`),
  INDEX `fk_Alumno_Materia1_idx` (`Materia_CodigoMateria` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Materia1`
    FOREIGN KEY (`Materia_CodigoMateria`)
    REFERENCES `Escuela`.`Materia` (`CodigoMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Enseñanza y Evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escuela`.`Enseñanza y Evaluacion` ;

CREATE TABLE IF NOT EXISTS `Escuela`.`Enseñanza y Evaluacion` (
  `Profesor_codigo` INT NOT NULL,
  `Alumno_Identificacion` INT NOT NULL,
  PRIMARY KEY (`Profesor_codigo`, `Alumno_Identificacion`),
  INDEX `fk_Profesor_has_Alumno_Alumno1_idx` (`Alumno_Identificacion` ASC) VISIBLE,
  INDEX `fk_Profesor_has_Alumno_Profesor_idx` (`Profesor_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_has_Alumno_Profesor`
    FOREIGN KEY (`Profesor_codigo`)
    REFERENCES `Escuela`.`Profesor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_has_Alumno_Alumno1`
    FOREIGN KEY (`Alumno_Identificacion`)
    REFERENCES `Escuela`.`Alumno` (`Identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
